### PR TITLE
some simple T470 changes

### PR DESCRIPTION
**Pull request by ESProcessing**
Hey TLUCK, lets stay in sync.

### CODE REVIEW

**Comment by tluck** [comment]
this doesnt seem like a clean pull/merge? i presume all your changes in are in the DSDT.T470 folder?

**Comment by ESProcessing** [comment]
Yes they are. Don't fully understand it, maybe because I am behind you.

**Comment by tluck** [comment]
Ok i pulled in your DSDT.T470 set of files. so I think it is all good now. Glad this stuff is still working. The next box for my son will either be a T460 or T470 !

**Comment by ESProcessing** [comment]
I will try to sync the two repos ton of get or tomorrow.

In the last 6 months, just minor adjustments were made. Everything is
working great, and my T470 is just humming along.

My three kids are between 1st and 6th grade and currently use a custom Mac
Mini hackintosh for all their schoolwork.

Cheers,
Scott

**Pull request merged**
